name: build apps
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - apps/**

permissions:
  contents: read
  packages: write

jobs:
  push:
    name: "yolks:apps_${{ matrix.app }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app:
          - dotnet
          - java
          - nodejs
          - python
          - golang
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./apps/${{ matrix.app }}
          file: ./apps/${{ matrix.app }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/an-hosting/apps:${{ matrix.app }}