name: build n8n

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - n8n/**

jobs:
  push:
    name: "n8n:${{ matrix.version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - v0.237
          - v1.0
          - v1.1

    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/setup-qemu-action@v3
      
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and test Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./n8n
          file: ./n8n/n8n_${{ matrix.version }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          load: true
          tags: |
            ghcr.io/an-hosting/yolks:n8n::test

      - name: Test container
        run: |
          docker run --name n8n-test -d -p 5678:5678 ghcr.io/an-hosting/yolks:n8n::test
          sleep 10
          curl --fail http://localhost:5678 || exit 1
          docker logs n8n-test
          docker stop n8n-test

      - name: Build and push final image
        uses: docker/build-push-action@v5
        with:
          context: ./n8n
          file: ./n8n/n8n_${{ matrix.version }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/an-hosting/yolks:n8n:latest
            ghcr.io/an-hosting/yolks:n8n:${{ matrix.version }} 