name: build n8n

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - n8n/**

jobs:
  push:
    name: "yolks:n8n_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - '0.237'
          - '1.0'
          - '1.1'

    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/setup-qemu-action@v3
      
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: ./n8n/n8n_${{ matrix.tag }}
          file: ./n8n/n8n_${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/an-hosting/yolks:n8n_${{ matrix.tag }} 