name: Run All Workflows
on:
  workflow_dispatch:

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workflow: [
          'apps.yml',
          'base.yml',
          'bot.yml',
          'box64.yml',
          'bun.yml',
          'cassandra.yml',
          'dart.yml',
          'dotnet.yml',
          'elixir.yml',
          'erlang.yml',
          'games.yml',
          'go.yml',
          'installers.yml',
          'java.yml',
          'mariadb.yml',
          'mongodb.yml',
          'mono.yml',
          'nodejs.yml',
          'postgres.yml',
          'python.yml',
          'redis.yml',
          'rust.yml',
          'steamcmd.yml',
          'voice.yml'
        ]
    steps:
      - uses: actions/checkout@v4
      
      - name: Trigger Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: ${{ matrix.workflow }}
          token: ${{ secrets.GITHUB_TOKEN }} 