name: Run All Workflows
on:
  workflow_dispatch:

jobs:
  installers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trigger Installers Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: installers.yml
          token: ${{ secrets.GITHUB_TOKEN }}

  base:
    needs: installers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trigger Base Workflows
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: base.yml
          token: ${{ secrets.GITHUB_TOKEN }}

  core-runtimes:
    needs: installers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workflow: [
          'java.yml',
          'python.yml',
          'nodejs.yml',
          'go.yml'
        ]
    steps:
      - uses: actions/checkout@v4
      - name: Trigger Core Runtime Workflows
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: ${{ matrix.workflow }}
          token: ${{ secrets.GITHUB_TOKEN }}

  databases:
    needs: core-runtimes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workflow: [
          'mariadb.yml',
          'mongodb.yml',
          'postgres.yml',
          'redis.yml',
          'cassandra.yml'
        ]
    steps:
      - uses: actions/checkout@v4
      - name: Trigger Database Workflows
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: ${{ matrix.workflow }}
          token: ${{ secrets.GITHUB_TOKEN }}

  specialized-runtimes:
    needs: databases
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workflow: [
          'bun.yml',
          'rust.yml',
          'dotnet.yml',
          'mono.yml',
          'dart.yml',
          'elixir.yml',
          'erlang.yml'
        ]
    steps:
      - uses: actions/checkout@v4
      - name: Trigger Specialized Runtime Workflows
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: ${{ matrix.workflow }}
          token: ${{ secrets.GITHUB_TOKEN }}

  applications:
    needs: specialized-runtimes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workflow: [
          'box64.yml',
          'steamcmd.yml',
          'voice.yml',
          'games.yml',
          'bot.yml',
          'apps.yml'
        ]
    steps:
      - uses: actions/checkout@v4
      - name: Trigger Application Workflows
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: ${{ matrix.workflow }}
          token: ${{ secrets.GITHUB_TOKEN }}